# Generated by Django 2.2.24 on 2021-09-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210909_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
